
eureka:
  client:
    service-url: # EurekaServer的地址，现在是自己的地址，如果是集群，需要加上其它Server的地址。
      defaultZone: http://hanhao:123@euk2.com:8082/eureka/,http://hanhao:123@euk1.com:8081/eureka/
    register-with-eureka: true
    fetch-registry: true

spring:
  application:
    name: user-consumer
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      rate: 1
  boot:
    admin:
      client:
        url: http://localhost:3001
eureka-provider:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always